
import { Product } from "./ProductCard";

export const products: Product[] = [
  {
    id: 1,
    name: "Cemento Portland Buzzi",
    description: "Cemento di alta qualità per costruzioni durevoli e resistenti",
    category: "Cementi",
    image: "https://edilgroupshop.com/wp-content/uploads/2021/01/CEMENTO-BUZZI-UNICEM-325R_EDILGROUPSHOP.jpg",
  },
  {
    id: 2,
    name: "Rasante grigio Kerakoll Rasofino",
    description: "Rasante professionale per finiture di alta qualità",
    category: "Rasanti",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQtXUpX0eqJnZ1DMVW0ebDQmBjIci6KXBBNw&s",
  },
  {
    id: 3,
    name: "Rasante bianco Kerakoll Rasofino",
    description: "Rasante bianco per finiture perfette e di pregio",
    category: "Rasanti",
    image: "https://www.lovebrico.com/695-large_default/rasante-kerakoll-rasobuild-eco-top-fino-25-kg-12047-bianco.jpg",
  },
  {
    id: 4,
    name: "Colla C1 Buffa Grigia",
    description: "Adesivo cementizio per piastrelle in interni",
    category: "Colle",
    image: "https://imes.me.it/wp-content/uploads/2016/09/DURABOND-UNIVERSALE.jpg",
  },
  {
    id: 5,
    name: "Colla C1 Buffa Bianca",
    description: "Adesivo cementizio bianco per piastrelle in interni",
    category: "Colle",
    image: "https://edilpiazza.com/cdn/shop/files/150756.jpg?v=1721292568",
  },
  {
    id: 6,
    name: "Forati da 12",
    description: "Mattoni forati da 12cm per pareti divisorie interne",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 7,
    name: "Forati da 8",
    description: "Mattoni forati da 8cm per tramezzi e pareti divisorie",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 8,
    name: "Forati da 6",
    description: "Mattoni forati da 6cm per pareti leggere",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 9,
    name: "Forati da 4",
    description: "Mattoni forati piccoli da 4cm per rivestimenti",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 10,
    name: "Mattoni Pressati",
    description: "Mattoni pressati per murature a vista ed estetiche",
    category: "Mattoni",
    image: "https://www.wienerberger.it/var/commerce/products/wienerberger/products/wbs_it_website/wbs_it_website/laterizi_classici/846681/assets/asset3.imgTransformer/crop_1to1/lg-5/1559907165813/18005581.jpg",
  },
  {
    id: 11,
    name: "Gasbeton",
    description: "Blocchi in cemento cellulare per murature isolanti",
    category: "Mattoni",
    image: "https://possettiediliziasrl.com/wp-content/uploads/2021/11/GASBETON.webp",
  },
  {
    id: 12,
    name: "Blocchetti di tufo",
    description: "Blocchetti in tufo naturale per murature tradizionali",
    category: "Mattoni",
    image: "https://centroevergreen.it/wp-content/uploads/2018/11/tufo_04.jpg",
  },
  {
    id: 13,
    name: "Architrave",
    description: "Architrave prefabbricato per porte e finestre",
    category: "Strutture",
    image: "https://www.mpmoran.co.uk/media/mf_webp/jpg/media/catalog/product/cache/0e72eafe89bb59269f3634c09d3eb498/M/a/Marshalls_Standard_Bullnosed_Kerb_Straight_125x150x914mm-1.webp",
  },
  {
    id: 14,
    name: "Sabbia Lavata",
    description: "Sabbia fine per massetti e miscele cementizie di qualità",
    category: "Inerti",
    image: "https://www.canzianinerti.it/wp-content/uploads/2023/05/aggregato-naturale-sabbia-frantoio-lavata-min.jpg",
  },
  {
    id: 15,
    name: "Sabbia Bianca",
    description: "Sabbia bianca fine per finiture e lavori di pregio",
    category: "Inerti",
    image: "https://cavechizzola.it/wp-content/uploads/2015/06/Sabbia-0-5-1030x773.jpg",
  },
  {
    id: 16,
    name: "Sabbione",
    description: "Sabbione per malte e intonaci a grana media",
    category: "Inerti",
    image: "https://images.ctfassets.net/j4m9q0fykyy4/7vBcsGChlMKJkMKoFRlEOC/a133824242e696055060f9a061a57b8d/2020-08-mortier-b_C3_A9ton.jpg",
  },
  {
    id: 17,
    name: "Rimacinato fino (Azolo)",
    description: "Inerte rimacinato fine per sottofondi e riempimenti",
    category: "Inerti",
    image: "https://files.synapp.it/87689/foto/prodotti/B/1522143826912_rimacinato_B.jpg",
  },
  {
    id: 18,
    name: "Pietrisco (Ghiaia)",
    description: "Pietrisco per drenaggi e calcestruzzi",
    category: "Inerti",
    image: "https://www.egap.it/EGAP/wp-content/uploads/2022/08/PH026-Pietrisco-Scelto-Grande.jpg",
  },
  {
    id: 19,
    name: "Misto",
    description: "Misto granulometrico per sottofondi stradali",
    category: "Inerti",
    image: "https://www.superbeton.it/kimg/640/misto_granulare_stab.jpg",
  },
  {
    id: 20,
    name: "Cemento Bianco",
    description: "Cemento bianco per lavori di pregio e finiture estetiche",
    category: "Cementi",
    image: "https://www.tecnomat.it/pub/media/catalog/product/8/4/d/5/cemento_bianco_italcementi_kg_rocca_bianca_25030915_picture.jpg",
  },
  {
    id: 21,
    name: "Cemento Rapido",
    description: "Cemento a presa rapida per lavori che richiedono velocità",
    category: "Cementi",
    image: "https://amadosalvador.es/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/l/a/lampocem-25kg-1_1.jpg",
  },
  {
    id: 22,
    name: "Calce",
    description: "Calce idraulica naturale per intonaci e restauri",
    category: "Leganti",
    image: "https://www.shopcorrera.com/917-large_default/grassello-di-calce-25-kg.jpg",
  },
  {
    id: 23,
    name: "Polistirolo",
    description: "Pannelli in polistirolo per isolamento termico",
    variants: [
      { id: "1cm", name: "1 cm" },
      { id: "2cm", name: "2 cm" },
      { id: "3cm", name: "3 cm" },
      { id: "4cm", name: "4 cm" },
      { id: "5cm", name: "5 cm" },
      { id: "6cm", name: "6 cm" },
      { id: "7cm", name: "7 cm" },
      { id: "8cm", name: "8 cm" },
    ],
    category: "Isolanti",
    image: "https://www.centroimballo.it/18326-large_default/lastre-in-polistirolo.jpg",
  },
  {
    id: 24,
    name: "Rete per Cappotto",
    description: "Rete in fibra di vetro per sistemi a cappotto termico",
    category: "Accessori",
    image: "https://ecomerchant.co.uk/cdn/shop/files/Glass-Fibre-Mesh-Reinforcing-for-Render.png?v=1696937538&width=1000",
  },
  {
    id: 25,
    name: "Bacchette per Intonaco",
    description: "Bacchette per la realizzazione di spigoli su intonaci",
    category: "Accessori",
    image: "https://edil-store.it/5071-large_default/profilo-guida-a-t-per-intonaco-cm-280.jpg",
  },
  {
    id: 26,
    name: "Angolari",
    description: "Angolari in PVC per la protezione di spigoli e angoli",
    category: "Accessori",
    image: "https://laspada1776.it/dati/images/prodotti/2021/04/profilato-angolare-pvc-intonaco.jpg",
  },
  {
    id: 27,
    name: "Gocciolatoi",
    description: "Profili con gocciolatoio per balconi e davanzali",
    category: "Accessori",
    image: "https://i.ebayimg.com/images/g/WPgAAOSwv0RkDIQV/s-l1600.jpg",
  },
  {
    id: 28,
    name: "Rete PVC",
    description: "Rete in PVC per recinzioni e protezioni temporanee",
    category: "Accessori",
    image: "https://m.media-amazon.com/images/I/71D+I1JLpVL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 29,
    name: "Rete Elettrosaldata",
    description: "Rete elettrosaldata per armature e rinforzi",
    category: "Strutture",
    image: "https://www.uniferspa.com/wp-content/uploads/sites/5/2017/04/IMG_9428_rete.jpg",
  },
  {
    id: 30,
    name: "Tavole da Carpenteria",
    description: "Tavole in legno per carpenteria e casserature",
    variants: [
      { id: "5cm", name: "5 cm" },
      { id: "10cm", name: "10 cm" },
      { id: "12cm", name: "12 cm" },
    ],
    category: "Legname",
    image: "https://files.synapp.it/50859/foto/prodotti/B/1616842385701_tavola_carpenteria_B.jpg",
  },
  {
    id: 31,
    name: "Caldarella",
    description: "Secchio da muratore per impasti e trasporto materiali",
    category: "Attrezzature",
    image: "https://cdn.manomano.com/images/images_products/33559688/P/119662117_1.jpg",
  },
  {
    id: 32,
    name: "Carriola",
    description: "Carriola per trasporto materiali in cantiere",
    category: "Attrezzature",
    image: "https://www.maurer.ferritalia.it/archivio/CAT/MOD_15916_84532_cat.jpg",
  },
  {
    id: 33,
    name: "Onduline Catramate",
    description: "Lastre ondulate bituminose per coperture e tettoie",
    category: "Coperture",
    image: "https://www.infobuild.it/wp-content/uploads/lastre-copertura-onduline.jpg",
  },
  {
    id: 34,
    name: "Chiodi in Acciaio",
    description: "Chiodi in acciaio per fissaggi resistenti alla corrosione",
    category: "Ferramenta",
    image: "https://images.mondo-artista.it/out/pictures/generated/500_500/426954/Chiodi+in+acciaio+per+quadri.jpg",
  },
  {
    id: 35,
    name: "Chiodi da 6",
    description: "Chiodi comuni da 6 cm per lavori di carpenteria",
    category: "Ferramenta",
    image: "https://media.adeo.com/media/14338/media.jpg?width=3000&height=3000&format=jpg&quality=80&fit=bounds",
  },
  {
    id: 36,
    name: "Bobina Fil di Ferro",
    description: "Filo di ferro zincato in bobina per legature",
    category: "Ferramenta",
    image: "https://www.spaziverdistore.it/2022-large_default/bobina-fil-di-ferro-maurer-a-due-fili.jpg",
  },
  {
    id: 37,
    name: "Bacchette di Ferro",
    description: "Barre di ferro per armature e rinforzi",
    variants: [
      { id: "8mm", name: "8 mm" },
      { id: "10mm", name: "10 mm" },
    ],
    category: "Strutture",
    image: "https://m.media-amazon.com/images/I/51pRJRkCiwL.jpg",
  },
  {
    id: 38,
    name: "Opere Morte",
    description: "Supporti e strutture temporanee per costruzioni",
    category: "Strutture",
    image: "https://m.media-amazon.com/images/I/4196o-OVB6L.jpg",
  },
  {
    id: 39,
    name: "Guanti Maurer",
    description: "Guanti da lavoro resistenti per edilizia",
    category: "Sicurezza",
    image: "https://www.maurer.ferritalia.it/archivio/CAT/MOD_8333_98892_cat.jpg",
  },
  {
    id: 40,
    name: "Guaina Elastik",
    description: "Guaina elastomerica impermeabilizzante",
    variants: [
      { id: "5kg", name: "5 Kg" },
      { id: "10kg", name: "10 Kg" },
      { id: "20kg", name: "20 Kg" },
    ],
    category: "Impermeabilizzanti",
    image: "https://scandecasa.it/wp-content/uploads/2024/10/Immagineddw.jpg",
  },
  {
    id: 41,
    name: "Rotolo Guaina",
    description: "Rotolo di guaina bituminosa per impermeabilizzazioni",
    category: "Impermeabilizzanti",
    image: "https://m.media-amazon.com/images/I/610cN9yUoGL.jpg",
  },
  {
    id: 42,
    name: "Intonaco NH Premix",
    description: "Intonaco di alta qualità per interni ed esterni",
    category: "Intonaci",
    image: "https://premix.it/wp-content/uploads/2025/02/INTONACO-NH-a-mano.jpeg",
  },
  {
    id: 43,
    name: "Intonaco NH Premix Fibrato",
    description: "Intonaco fibrato per maggiore resistenza e durabilità",
    category: "Intonaci",
    image: "https://premix.it/wp-content/uploads/2025/02/INTONACO-NHF.jpeg",
  },
  {
    id: 44,
    name: "Tonachina T600",
    description: "Finitura fine per superfici intonacate",
    category: "Intonaci",
    image: "https://premix.it/wp-content/uploads/2022/09/Tonachina-T600.jpeg",
  },
  {
    id: 45,
    name: "Pala a Mano",
    description: "Pala manuale per lavori di scavo e movimento terra",
    category: "Attrezzature",
    image: "https://www.rubinosrl.it/13003-large_default/valsecchi-badile-acciaio-temperato-blu-mto.jpg",
  },
];

export const categories = [
  "Tutti", "Cementi", "Rasanti", "Colle", "Mattoni", "Inerti", "Coperture", 
  "Strutture", "Leganti", "Isolanti", "Accessori", "Legname", "Attrezzature", 
  "Ferramenta", "Sicurezza", "Impermeabilizzanti", "Intonaci"
];
