
import { Product } from "./ProductCard";

export const products: Product[] = [
  {
    id: 1,
    name: "Cemento Portland Buzzi",
    description: "Cemento di alta qualità per costruzioni durevoli e resistenti",
    category: "Cementi",
    image: "https://www.amorelegnamistore.it/cdn/shop/files/CEMENTO-425-BUZZI-PORTLAND-25-KG-Amorelegnami-310.jpg?v=1683920067&width=950",
  },
  {
    id: 2,
    name: "Rasante grigio Kerakoll Rasofino",
    description: "Rasante professionale per finiture di alta qualità",
    category: "Rasanti",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQtXUpX0eqJnZ1DMVW0ebDQmBjIci6KXBBNw&s",
  },
  {
    id: 3,
    name: "Rasante bianco Kerakoll Rasofino",
    description: "Rasante bianco per finiture perfette e di pregio",
    category: "Rasanti",
    image: "https://www.lovebrico.com/695-large_default/rasante-kerakoll-rasobuild-eco-top-fino-25-kg-12047-bianco.jpg",
  },
  {
    id: 4,
    name: "Colla C1 Buffa Grigia",
    description: "Adesivo cementizio per piastrelle in interni",
    category: "Colle",
    image: "https://imes.me.it/wp-content/uploads/2016/09/DURABOND-UNIVERSALE.jpg",
  },
  {
    id: 5,
    name: "Colla C1 Buffa Bianca",
    description: "Adesivo cementizio bianco per piastrelle in interni",
    category: "Colle",
    image: "https://edilpiazza.com/cdn/shop/files/150756.jpg?v=1721292568",
  },
  {
    id: 6,
    name: "Forati da 12",
    description: "Mattoni forati da 12cm per pareti divisorie interne",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 7,
    name: "Forati da 8",
    description: "Mattoni forati da 8cm per tramezzi e pareti divisorie",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 8,
    name: "Forati da 6",
    description: "Mattoni forati da 6cm per pareti leggere",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 9,
    name: "Forati da 4",
    description: "Mattoni forati piccoli da 4cm per rivestimenti",
    category: "Mattoni",
    image: "https://www.danesilaterizi.it/wp-content/uploads/2020/01/Quattro-fori-8.12.24.jpg",
  },
  {
    id: 10,
    name: "Mattoni Pressati",
    description: "Mattoni pressati per murature a vista ed estetiche",
    category: "Mattoni",
    image: "https://www.amicoflex.it/wp-content/uploads/2020/07/Ecobonus-110-e-mattoni-1200x900.jpeg",
  },
  {
    id: 11,
    name: "Gasbeton",
    description: "Blocchi in cemento cellulare per murature isolanti",
    category: "Mattoni",
    image: "https://www.tekneco.it/immagini/articoli/gasbeton.jpg",
  },
  {
    id: 12,
    name: "Blocchetti di tufo",
    description: "Blocchetti in tufo naturale per murature tradizionali",
    category: "Mattoni",
    image: "https://www.casacapitolatosupplies.it/data/photos/6767_1blocchi_tufacei_lisci_12x25x37.jpeg",
  },
  {
    id: 13,
    name: "Architrave",
    description: "Architrave prefabbricato per porte e finestre",
    category: "Strutture",
    image: "https://img.edilportale.com/product-thumbs/h_Gallotta_ARCHITRAVE-2x2x5_mcHgJrPOS8.jpeg",
  },
  {
    id: 14,
    name: "Sabbia Lavata",
    description: "Sabbia fine per massetti e miscele cementizie di qualità",
    category: "Inerti",
    image: "https://www.canzianinerti.it/wp-content/uploads/2023/05/aggregato-naturale-sabbia-frantoio-lavata-min.jpg",
  },
  {
    id: 15,
    name: "Sabbia Bianca",
    description: "Sabbia bianca fine per finiture e lavori di pregio",
    category: "Inerti",
    image: "https://cavechizzola.it/wp-content/uploads/2015/06/Sabbia-0-5-1030x773.jpg",
  },
  {
    id: 16,
    name: "Sabbione",
    description: "Sabbione per malte e intonaci a grana media",
    category: "Inerti",
    image: "https://images.ctfassets.net/j4m9q0fykyy4/7vBcsGChlMKJkMKoFRlEOC/a133824242e696055060f9a061a57b8d/2020-08-mortier-b_C3_A9ton.jpg",
  },
  {
    id: 17,
    name: "Rimacinato fino (Azolo)",
    description: "Inerte rimacinato fine per sottofondi e riempimenti",
    category: "Inerti",
    image: "https://files.synapp.it/87689/foto/prodotti/B/1522143826912_rimacinato_B.jpg",
  },
  {
    id: 18,
    name: "Pietrisco (Ghiaia)",
    description: "Pietrisco per drenaggi e calcestruzzi",
    category: "Inerti",
    image: "https://www.egap.it/EGAP/wp-content/uploads/2022/08/PH026-Pietrisco-Scelto-Grande.jpg",
  },
  {
    id: 19,
    name: "Misto",
    description: "Misto granulometrico per sottofondi stradali",
    category: "Inerti",
    image: "https://www.superbeton.it/kimg/640/misto_granulare_stab.jpg",
  },
  {
    id: 20,
    name: "Cemento Bianco",
    description: "Cemento bianco per lavori di pregio e finiture estetiche",
    category: "Cementi",
    image: "https://m.media-amazon.com/images/I/71IWkQU+HdL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 21,
    name: "Cemento Rapido",
    description: "Cemento a presa rapida per lavori che richiedono velocità",
    category: "Cementi",
    image: "https://www.fassabortolo.it/media/products/2020_GEOACTIVE_RAPID_5_25kg-640x640.png",
  },
  {
    id: 22,
    name: "Calce",
    description: "Calce idraulica naturale per intonaci e restauri",
    category: "Leganti",
    image: "https://caetani.com/wp-content/uploads/2021/06/calceacquasale.jpg",
  },
  {
    id: 23,
    name: "Polistirolo",
    description: "Pannelli in polistirolo per isolamento termico",
    variants: [
      { id: "1cm", name: "1 cm" },
      { id: "2cm", name: "2 cm" },
      { id: "3cm", name: "3 cm" },
      { id: "4cm", name: "4 cm" },
      { id: "5cm", name: "5 cm" },
      { id: "6cm", name: "6 cm" },
      { id: "7cm", name: "7 cm" },
      { id: "8cm", name: "8 cm" },
    ],
    category: "Isolanti",
    image: "https://www.isolconfort.it/image/cache/catalog/prodotti/POLICEM-1200x800.jpg",
  },
  {
    id: 24,
    name: "Rete per Cappotto",
    description: "Rete in fibra di vetro per sistemi a cappotto termico",
    category: "Accessori",
    image: "https://ecomerchant.co.uk/cdn/shop/files/Glass-Fibre-Mesh-Reinforcing-for-Render.png?v=1696937538&width=1000",
  },
  {
    id: 25,
    name: "Bacchette per Intonaco",
    description: "Bacchette per la realizzazione di spigoli su intonaci",
    category: "Accessori",
    image: "https://parisi.passepartout.cloud/upload/articoli/PU6PB_1_800.jpg",
  },
  {
    id: 26,
    name: "Angolari",
    description: "Angolari in PVC per la protezione di spigoli e angoli",
    category: "Accessori",
    image: "https://laspada1776.it/dati/images/prodotti/2021/04/profilato-angolare-pvc-intonaco.jpg",
  },
  {
    id: 27,
    name: "Gocciolatoi",
    description: "Profili con gocciolatoio per balconi e davanzali",
    category: "Accessori",
    image: "https://i.ebayimg.com/images/g/WPgAAOSwv0RkDIQV/s-l1600.jpg",
  },
  {
    id: 28,
    name: "Rete PVC",
    description: "Rete in PVC per recinzioni e protezioni temporanee",
    category: "Accessori",
    image: "https://m.media-amazon.com/images/I/81eRX9kDaZL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 29,
    name: "Rete Elettrosaldata",
    description: "Rete elettrosaldata per armature e rinforzi",
    category: "Strutture",
    image: "https://edilpiazza.it/wp-content/uploads/2022/07/rete-elettrosaldata-gruppo-ormea-edilpiazza.jpg",
  },
  {
    id: 30,
    name: "Tavole da Carpenteria",
    description: "Tavole in legno per carpenteria e casserature",
    variants: [
      { id: "5cm", name: "5 cm" },
      { id: "10cm", name: "10 cm" },
      { id: "12cm", name: "12 cm" },
    ],
    category: "Legname",
    image: "https://www.legnamipretagliatiroma.it/wp-content/uploads/2023/01/assi-di-legno.jpg",
  },
  {
    id: 31,
    name: "Caldarella",
    description: "Secchio da muratore per impasti e trasporto materiali",
    category: "Attrezzature",
    image: "https://www.kijiji.it/photo.php?bucket=12&p=18&geo=9030&photo=2312795118.jpg",
  },
  {
    id: 32,
    name: "Carriola",
    description: "Carriola per trasporto materiali in cantiere",
    category: "Attrezzature",
    image: "https://www.scuoladeisaberi.it/images/thumbnails/1110/750/detailed/151/0f12a1ab9c4f4bd6a142e4d33c5e16ec~2.png",
  },
  {
    id: 33,
    name: "Onduline Catramate",
    description: "Lastre ondulate bituminose per coperture e tettoie",
    category: "Coperture",
    image: "https://www.infobuild.it/wp-content/uploads/lastre-copertura-onduline.jpg",
  },
  {
    id: 34,
    name: "Chiodi in Acciaio",
    description: "Chiodi in acciaio per fissaggi resistenti alla corrosione",
    category: "Ferramenta",
    image: "https://www.unichiodi.it/31-large_default/2d-chiodi-in-acciaio-inox-aisi-304-punta-diamante.jpg",
  },
  {
    id: 35,
    name: "Chiodi da 6",
    description: "Chiodi comuni da 6 cm per lavori di carpenteria",
    category: "Ferramenta",
    image: "https://ilferramenta.com/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWMvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2fff6e0b8a0ad7edc3de01babb7d2ecec8b6ad0e/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9TY21WemFYcGxYM1J2WDJacGJHeGJCMmtDWkFOcEFuZ0Q2QjRjR0ZzWVhSZmQyaHBkR1VLWVFOcEFtZ0MiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--a7e9caa1af60e41d6b9ff2d5d7264b12ef52cdee/450-chiodi-stella-testa-larga-4x70mm.jpg?locale=it",
  },
  {
    id: 36,
    name: "Bobina Fil di Ferro",
    description: "Filo di ferro zincato in bobina per legature",
    category: "Ferramenta",
    image: "https://media.leroymerlin.it/media/high_res_images/88110/88110106_4.jpg?width=1170&amp;height=770",
  },
  {
    id: 37,
    name: "Bacchette di Ferro",
    description: "Barre di ferro per armature e rinforzi",
    variants: [
      { id: "8mm", name: "8 mm" },
      { id: "10mm", name: "10 mm" },
    ],
    category: "Strutture",
    image: "https://media.ideegreen.it/SXg6_-3nw0W-ZbzxsEYJu3UROAc=/600x450/https://media.ideegreen.it/1/t/tondino-di-ferro.jpg",
  },
  {
    id: 38,
    name: "Opere Morte",
    description: "Supporti e strutture temporanee per costruzioni",
    category: "Strutture",
    image: "https://www.tecnologica.it/wp-content/uploads/2020/12/passerelle-tecnologica.jpg",
  },
  {
    id: 39,
    name: "Guanti Maurer",
    description: "Guanti da lavoro resistenti per edilizia",
    category: "Sicurezza",
    image: "https://www.coltelleriamaurer.com/wp-content/uploads/2020/03/5C99D78F-00C6-42C1-8EB1-E0D89A88CED5-scaled.jpeg",
  },
  {
    id: 40,
    name: "Guaina Elastik",
    description: "Guaina elastomerica impermeabilizzante",
    variants: [
      { id: "5kg", name: "5 Kg" },
      { id: "10kg", name: "10 Kg" },
      { id: "20kg", name: "20 Kg" },
    ],
    category: "Impermeabilizzanti",
    image: "https://www.buffa.it/wp-content/uploads/2023/08/elastik-20-kg.png",
  },
  {
    id: 41,
    name: "Rotolo Guaina",
    description: "Rotolo di guaina bituminosa per impermeabilizzazioni",
    category: "Impermeabilizzanti",
    image: "https://m.media-amazon.com/images/I/41uH5Qx4cNL._AC_UF1000,1000_QL80_.jpg",
  },
];

export const categories = [
  "Tutti", "Cementi", "Rasanti", "Colle", "Mattoni", "Inerti", "Coperture", 
  "Strutture", "Leganti", "Isolanti", "Accessori", "Legname", "Attrezzature", 
  "Ferramenta", "Sicurezza", "Impermeabilizzanti"
];
